{
 "title": "Strava Dashboard",
 "time": { "from": "now/y -9y", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "type",
    "label": "Activity Type",
    "query": "select activity_type from activities;"
   }
  ]
 },
 "panels": [
  { "title": "This Week", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "No of activities",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "7d" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "activities",
     "query": "SELECT count(\"distance\") FROM \"activities\" WHERE activity_type in ($type) AND $__timeFilter(time); ",
     "rawSql": "SELECT count(\"distance\") FROM \"activities\" WHERE activity_type in ($type) AND $__timeFilter(time);\n"
    }
   ]
  },
  {
   "title": "Distance",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "lengthm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "7d" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "activities",
     "query": "SELECT sum(\"distance\") FROM \"activities\" WHERE activity_type in ($type) AND $__timeFilter(time);",
     "rawSql": "SELECT sum(\"distance\") FROM \"activities\" WHERE activity_type in ($type) AND $__timeFilter(time);"
    }
   ]
  },
  {
   "title": "Time",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "7d" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "activities",
     "query": "SELECT sum(\"duration\") FROM \"activities\" WHERE activity_type in ($type) AND $__timeFilter(time);",
     "rawSql": "SELECT sum(\"duration\") FROM \"activities\" WHERE activity_type in ($type) AND $__timeFilter(time);"
    }
   ]
  },
  {
   "title": "Elevation",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "activities",
     "query": "SELECT sum(\"elevation\") FROM \"activities\" WHERE activity_type in ($type) AND $__timeFilter(time);",
     "rawSql": "SELECT sum(\"elevation\") FROM \"activities\" WHERE activity_type in ($type) AND $__timeFilter(time);"
    }
   ]
  },
  { "title": "This Year", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "Yeardistance",
   "type": "bargauge",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "lengthm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "activities",
     "query": "SELECT sum(\"distance\") FROM \"activities\" WHERE activity_type in ($type) AND $__timeFilter(time);",
     "rawSql": "SELECT sum(\"distance\") FROM \"activities\" WHERE activity_type in ($type) AND $__timeFilter(time);"
    }
   ]
  },
  {
   "title": "Longest Activity",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "lengthm" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "measurement": "activities",
     "query": "SELECT \"distance\" FROM \"activities\" WHERE activity_type in ($type) AND $__timeFilter(time);",
     "rawSql": "SELECT \"distance\" FROM \"activities\" WHERE activity_type in ($type) AND $__timeFilter(time);"
    }
   ]
  },
  {
   "title": "Max Speed",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "velocitykmh" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "measurement": "activities",
     "query": "SELECT \"max_speed\" FROM \"activities\" WHERE activity_type in ($type) AND $__timeFilter(time);",
     "rawSql": "SELECT \"max_speed\" FROM \"activities\" WHERE activity_type in ($type) AND $__timeFilter(time);"
    }
   ]
  },
  {
   "title": "Max Elevation",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "lengthm" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "measurement": "activities",
     "query": "SELECT \"elevation\" FROM \"activities\" WHERE activity_type in ($type) AND $__timeFilter(time);",
     "rawSql": "SELECT \"elevation\" FROM \"activities\" WHERE activity_type in ($type) AND $__timeFilter(time);"
    }
   ]
  },
  {
   "title": "Max max Power",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "measurement": "activities",
     "query": "SELECT \"max_watts\" FROM \"activities\" WHERE activity_type in ($type) AND $__timeFilter(time);",
     "rawSql": "SELECT \"max_watts\" FROM \"activities\" WHERE activity_type in ($type) AND $__timeFilter(time);"
    }
   ]
  },
  {
   "title": "No of activities",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 14 },
   "targets": [
    {
     "alias": "$tag_type",
     "groupBy": [
      { "params": [ "type" ], "type": "tag" }
     ],
     "measurement": "activities",
     "query": "SELECT count(\"distance\") FROM \"activities\" WHERE $timeFilter GROUP BY \"activity_type\"",
     "rawSql": "SELECT count(\"distance\"), activity_type FROM \"activities\" WHERE $__timeFilter(time) GROUP BY activity_type;"
    }
   ]
  },
  {
   "title": "Activities",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "lengthm" } },
   "targets": [
    {
     "measurement": "activities",
     "query": "SELECT \"distance\", \"duration\" FROM \"activities\" WHERE activity_type in ($type) AND $__timeFilter(time);",
     "rawSql": "SELECT \"distance\", \"duration\", \"time\" FROM \"activities\" WHERE activity_type in ($type) AND $__timeFilter(time);"
    }
   ]
  },
  {
   "title": "Overall",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 },
   "collapsed": true,
   "panels": [
    {
     "title": "Totaldistance",
     "type": "stat",
     "gridPos": { "h": 5, "w": 8, "x": 0, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "lengthm" } },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "measurement": "activities",
       "query": "SELECT \"distance\" FROM \"activities\" WHERE activity_type in ($type) AND $__timeFilter(time);",
       "rawSql": "SELECT \"distance\", time FROM \"activities\" WHERE activity_type in ($type) AND $__timeFilter(time);"
      }
     ]
    },
    {
     "title": "Totaltime",
     "type": "stat",
     "gridPos": { "h": 5, "w": 8, "x": 8, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "measurement": "activities",
       "query": "SELECT \"duration\" FROM \"activities\" WHERE activity_type in ($type) AND $__timeFilter(time);",
       "rawSql": "SELECT \"duration\", time FROM \"activities\" WHERE activity_type in ($type) AND $__timeFilter(time);"
      }
     ]
    },
    {
     "title": "Total Number of Activities",
     "type": "stat",
     "gridPos": { "h": 5, "w": 8, "x": 16, "y": 34 },
     "options": { "reduceOptions": { "calcs": [ "count" ] } },
     "targets": [
      {
       "measurement": "activities",
       "rawSql": "SELECT \"distance\" FROM \"activities\" WHERE activity_type in ($type) AND $__timeFilter(time)"
      }
     ]
    },
    {
     "title": "Longest Activity",
     "type": "stat",
     "gridPos": { "h": 5, "w": 6, "x": 0, "y": 39 },
     "fieldConfig": { "defaults": { "unit": "lengthm" } },
     "options": { "reduceOptions": { "calcs": [ "max" ] } },
     "targets": [
      {
       "measurement": "activities",
       "query": "SELECT \"distance\" FROM \"activities\" WHERE activity_type in ($type) AND $__timeFilter(time);",
       "rawSql": "SELECT \"distance\" FROM \"activities\" WHERE activity_type in ($type) AND $__timeFilter(time);"
      }
     ]
    },
    {
     "title": "Max Elevation",
     "type": "stat",
     "gridPos": { "h": 5, "w": 6, "x": 6, "y": 39 },
     "fieldConfig": { "defaults": { "unit": "lengthm" } },
     "options": { "reduceOptions": { "calcs": [ "max" ] } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "7d" ], "type": "time" },
        { "params": [ "previous" ], "type": "fill" }
       ],
       "measurement": "activities",
       "query": "SELECT \"elevation\" FROM \"activities\" WHERE activity_type in ($type) AND $__timeFilter(time);",
       "rawSql": "SELECT \"elevation\" FROM \"activities\" WHERE activity_type in ($type) AND $__timeFilter(time);"
      }
     ]
    },
    {
     "title": "Max Speed",
     "type": "stat",
     "gridPos": { "h": 5, "w": 6, "x": 12, "y": 39 },
     "fieldConfig": { "defaults": { "unit": "velocitykmh" } },
     "options": { "reduceOptions": { "calcs": [ "max" ] } },
     "targets": [
      {
       "measurement": "activities",
       "query": "SELECT \"max_speed\" FROM \"activities\" WHERE activity_type in ($type) AND $__timeFilter(time);",
       "rawSql": "SELECT \"max_speed\" FROM \"activities\" WHERE activity_type in ($type) AND $__timeFilter(time) AND max_speed < 130;"
      }
     ]
    },
    {
     "title": "Max Power",
     "type": "stat",
     "gridPos": { "h": 5, "w": 6, "x": 18, "y": 39 },
     "fieldConfig": { "defaults": { "unit": "watt" } },
     "options": { "reduceOptions": { "calcs": [ "max" ] } },
     "targets": [
      {
       "measurement": "activities",
       "rawSql": "SELECT \"max_watts\" FROM \"activities\" WHERE activity_type in ($type) AND $__timeFilter(time);"
      }
     ]
    },
    {
     "title": "Panel Title",
     "type": "stat",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 44 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "alias": "$tag_name",
       "groupBy": [
        { "params": [ "name" ], "type": "tag" }
       ],
       "measurement": "segments",
       "query": "SELECT min(\"prtime\") as time FROM \"segments\" WHERE $timeFilter GROUP BY \"name\"",
       "rawSql": "SELECT min(\"prtime\") as time FROM \"segments\" WHERE $__timeFilter(time) GROUP BY \"name\""
      }
     ]
    },
    {
     "title": "Yearly Distances",
     "type": "bargauge",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 44 },
     "fieldConfig": { "defaults": { "unit": "lengthm" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "alias": "$tag_year",
       "groupBy": [
        { "params": [ "year" ], "type": "tag" }
       ],
       "measurement": "activities",
       "query": "SELECT sum(\"distance\") FROM \"activities\" WHERE activity_type in ($type) AND $__timeFilter(time);  GROUP BY \"year\"",
       "rawSql": "SELECT sum(\"distance\"), year FROM \"activities\" WHERE activity_type in ($type) AND $__timeFilter(time) GROUP BY \"year\" ORDER BY \"year\";"
      }
     ]
    },
    {
     "title": "Yearly Distance Progress",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 54 },
     "fieldConfig": { "defaults": { "unit": "lengthm" } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "year" ], "type": "tag" }
       ],
       "measurement": "activities",
       "query": "SELECT cumulative_sum(\"distance\") as distance, cumulative_sum(\"elevation\") as elevation FROM \"activities\" WHERE activity_type in ($type) AND $__timeFilter(time);  GROUP BY \"year\"",
       "select": [
        [
         { "params": [ "distance" ], "type": "field" },
         {
          "params": [],
          "type": "cumulative_sum"
         }
        ],
        [
         { "params": [ "elevation" ], "type": "field" },
         {
          "params": [],
          "type": "cumulative_sum"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Yearly Duration Progress",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 65 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "alias": "$tag_year",
       "query": "SELECT cumulative_sum(\"duration\") as \"duration\" FROM \"activities\" WHERE activity_type in ($type) AND $__timeFilter(time);  GROUP BY \"year\""
      }
     ]
    }
   ]
  }
 ]
}